### ISSUE TITLE
A few gotcha's coming from Slim

### ISSUE THREAD

**Issue by fossfool** [mattn/go-slim#6]
All in all, I'm very impressed with your library. I ran into a few issues transferring slim files from another project:

* Multiline support
* javascript: keyword doesn't exist / work for me.

Work arounds: Turn on word wrap in your editor, and move js to external file. 

How difficult would these be to implement / would you be interested in adding the functionality?

-James

**Comment by mattn** [comment]
I'm not familier to slim spec. Could you please show me what you want?

**Comment by fossfool** [comment]
Hey There!

Check out the example on their page: http://slim-lang.com

For clarity, let's say the preceding periods "." represent tabs or indents in my examples. If you're code looks like:

javascript:
. alert('Line 1');
. alert("Line 2");
. alert("Line 3");

You'll get:
<script>
. alert('Line 1');
. alert("Line 2");
. alert("Line 3");
</script>

Or this code is cut straight out of one of my templates:

. . javascript:
. . . function getCookieValue(a) {
. . . . let b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
. . . . return b ? b.pop() : '';
. . . }
. . . 
. . . const gpdr = getCookieValue("GDPR");
. . . if(gpdr) {
. . . . document.getElementById("gdpr-message").style.display = 'none';
. . . } else {
. . . . document.getElementById("gdpr-message").style.display = "";
. . . };

Output:

. . <script>
. . . function getCookieValue(a) {
. . . . let b = document.cookie.match('(^|;)\\s*' + a + '\\s*=\\s*([^;]+)');
. . . . return b ? b.pop() : '';
. . . }
. . . 
. . . const gpdr = getCookieValue("GDPR");
. . . if(gpdr) {
. . . . document.getElementById("gdpr-message").style.display = 'none';
. . . } else {
. . . . document.getElementById("gdpr-message").style.display = "";
. . . };
. . </script>

For multiline text:

. . . p This is line 1.
. . . . This is line 2.
. . . . This is line 3.

Output:

. . . <p>
. . . .	This is line 1. 
. . . . This is line 2. 
. . . . This is line 3.
. . . </p>

The is the indentation after the p on the second line. It just makes managing source code a little bit easier to read and follow.

Does this make sense?

Thanks,
-james

**Comment by fossfool** [comment]
Another difference I ran across is dashes "-" in id names fail:

. . . button id="btn-learn-more" Learn More

Won't compile, but does in Slim. This is more minor and not sure how easy it would be to correct.

**Comment by mattn** [comment]
As far as I'm trying some cases with slimrb, it seems that slimrb treat javascript: as special case.

```slim
head
  javascript:
    var a = {
      javascript:
        alert(1),
      p foo=bar
    }
```
```
<head><script>var a = {
  javascript:
    alert(1),
  p foo=bar
}</script></head>
```

**Comment by mattn** [comment]
Addressed https://github.com/mattn/go-slim/pull/7
